version: '3.6'

services:
  web:
    restart: always
    container_name: applab
    build: ./applab
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./applab/:/usr/src/applab/
    ports:
      - 8001:8001
    depends_on:
      - db
  db:
    restart: always
    container_name: applabdb
    image: postgres
    environment:
      - POSTGRES_USER=develop
      - POSTGRES_DB=develop
      - POSTGRES_PASSWORD=DYcsGQdjWhB8
