# Generated by Django 2.2.7 on 2021-10-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=256, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=256, verbose_name='Correo electrónico')),
                ('area', models.CharField(max_length=256, verbose_name='Área')),
                ('estatus', models.CharField(max_length=256, verbose_name='Estatus')),
                ('foto', models.FileField(upload_to='', verbose_name='Foto de perfil')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
    ]
